version: '3.8'

services:
  backend:
    container_name: students_backend
    build: ./backend
    expose:
      - "3000"
    networks:
      - students_network
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=postgres
      - PGPORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:16.9
    container_name: students_database
    expose:
      - "5432"
    networks:
      - students_network
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:alpine
    container_name: students_nginx
    networks:
      - students_network
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

networks:
  students_network:
    driver: bridge
    name: students_network
